# Generated by Django 5.2.4 on 2025-07-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(verbose_name=255)),
                ('lastName', models.CharField(verbose_name=255)),
                ('userName', models.CharField(verbose_name=255)),
                ('password', models.CharField(verbose_name=255)),
            ],
        ),
    ]
