# Generated by Django 5.2.4 on 2025-07-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middleName',
            field=models.CharField(default='Bongo Boltu', verbose_name=255),
        ),
    ]
