# Generated by Django 5.2.4 on 2025-07-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_customuser_middlename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='CustomUser_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='CustomUser_email',
            field=models.EmailField(default=2, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
