# Generated by Django 5.2.4 on 2025-07-23 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_customuser_id_customuser_customuser_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('Brand_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Brand_name', models.CharField(verbose_name=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Category_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Category_name', models.CharField(verbose_name=255)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='CustomUser_email',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Customer_phone', models.CharField(max_length=20)),
                ('Customer_address', models.CharField(max_length=255)),
                ('CustomUser_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('Cart_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Cart_created_at', models.DateTimeField(auto_now_add=True)),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('ActivityLog_ID', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('Notification_ID', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('Notification_created_at', models.DateTimeField(auto_now_add=True)),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Order_status', models.CharField(max_length=255)),
                ('Order_created_at', models.DateTimeField(auto_now_add=True)),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Payment_ID', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('Payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Bkash', 'Bkash'), ('Nagad', 'Nagad')], max_length=50)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('Order_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Product_name', models.CharField(verbose_name=255)),
                ('Product_description', models.TextField()),
                ('Brand_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
                ('Category_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('ProductVariant_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductVariant_name', models.CharField(verbose_name=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('OrderItem_ID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderItem_quantity', models.IntegerField()),
                ('Order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.order')),
                ('ProductVariant_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('CartItem_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CartItem_quantity', models.CharField(verbose_name=255)),
                ('Cart_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.cart')),
                ('ProductVariant_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('ReturnRequest_ID', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=255)),
                ('is_approved', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('OrderItem_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('Review_ID', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(max_length=255)),
                ('Review_created_at', models.DateTimeField(auto_now_add=True)),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.customer')),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('ShippingAddress_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ShippingAddress_address', models.CharField(verbose_name=255)),
                ('city', models.CharField(default='Unknown', max_length=255)),
                ('postal_code', models.CharField(default='0000', max_length=20)),
                ('country', models.CharField(max_length=255)),
                ('Order_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.order')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('StopIteration_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('Customer_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('Wishlist_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.customer')),
                ('ProductVariant_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant')),
            ],
        ),
    ]
